# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
    command = "npm run build"
    publish="build/"
    base = "client/"

[context.production]
    environment = { API_HOST = "https://isoyute-word-finder-server.herokuapp.com:5050" }